name = input ("hello! what is your name? ˚⟡°❀⋆.ೃ࿔* ࣪")
print (f"hello {name}! ୨୧ today we will tell a story with your help!")
color = input ("please pick a color")
adjective = input ("now please pick an adjective")
animal = input ("lastly, please pick an animal")
print ("･ ⋆ ･ ⠄⠂⋆ ･ ⠄⠂⋆ ･ ⠄･ ⋆ ･ ⠄⠂⋆ ･ ⠄⠂⋆ ･ ⠄")
print ("our story starts here ✧˚₊‧")
print (".........♡..........")
print (f"it was a {color}, {adjective} night. a {animal} was walking down the beach")
print ("...........................................................................")
print ("ooh! what a... uh... cool... start to our story! let's keep going!!!")
another_animal = input ("please pick another animal")
verb = input ("now pick a verb ending in 'ing'")
print ("ok, let's see what happens next!")
print ("................................................")
print (f"the {animal} saw a {another_animal} {verb}.")
print (f"the {animal} saw this and ran over to the {another_animal} to ask why.")
print ("..........................................................")
print ("wow! this story is...interesting...isn't it?")
print ("let's finish off our story!")
print ("..........................................................")
verb_3 = input ("pick another verb ending in 'ing'")
verb_ed = input ("pick a verb ending in 'ed'")
food = input ("pick a yummy food!")
print ("ok, here it goes...")
print (".......................................")
print (f"the {another_animal} {verb_3}, 'i don't have a friend to share my {food} with!!!'")
print (f"well, said the {animal}, I'll share your {food} with you!")
print ("..........................................................")
print ("ok...hmm... let's put this story together!!!!")
print ("⤷")
print (f"it was a {color}, {adjective} night. a {animal} was walking down the beach.")
print (f"the {animal} saw a {another_animal} {verb}.")
print (f" the {animal} saw this and ran over to the {another_animal} to ask why.")
print (f"the {another_animal} {verb_3}, 'i don't have a friend to share my {food} with!!!")
print (f"'well, said the {animal}, I'll share your {food} with you!")
print ("˚✧ THE END ✧˚₊‧")
print (".................................................")
print ("you did it! that was definitely a..uh... WEIRD story, but... good job!!!")
print ("°❀⋆.ೃ࿔*:･")